source 'https://github.com/CocoaPods/Specs.git'
# ignore all warnings from all pods
inhibit_all_warnings!
workspace 'estate.xcworkspace'

platform :ios, '8.0'

target 'estate' do
  pod 'AFNetworking'
  pod 'FMDB'
  pod 'JSONKit-NoWarning','1.2'
  pod 'libextobjc/EXTScope', '~> 0.4'
  pod 'WebViewJavascriptBridge', '~> 4.1'
  pod 'KVOController', '~> 1.0.3'
  pod 'MBProgressHUD', '~> 0.9'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'Masonry'
  #集成腾讯的错误收集分析工具'Bugly'
  pod 'Bugly'
  pod 'LPDQuoteImagesView'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  project './estate.xcodeproj'
#  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
#  pod 'RNFS', :path => '../node_modules/react-native-fs'
#  pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive'
  pod 'UMCCommon'
#  pod 'UMCSecurityPlugins'
  pod 'UMCShare/UI'
  # 集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedWeChat'
  # 集成新浪微博(精简版1M)
  pod 'UMCShare/Social/ReducedSina'
  # 集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMCShare/Social/ReducedQQ'
  # 集成邮件
  pod 'UMCShare/Social/Email'
  # 集成短信
  pod 'UMCShare/Social/SMS'
end
target 'CKSecurityTool' do
  project './CKSecurityTool/CKSecurityTool.xcodeproj'
end
