export const FORGOT_IMAGE_CODE = 'FORGOT_IMAGE_CODE'
export const FORGOT_USER_CHECK = 'FORGOT_USER_CHECK'
export const FORGOT_PHONE_CODE = 'FORGOT_PHONE_CODE'
export const FORGOT_PHONE_CODE_VERIFY = 'FORGOT_PHONE_CODE_VERIFY' // 
export const FORGOT_ERROR = 'FORGOT_ERROR'
export const FORGOT_RESET = 'FORGOT_RESET'
export const FORGOT_STEP = 'FORGOT_STEP'

