
export const CHANGE_PROJECT_LIST_DOING = 'CHANGE_PROJECT_LIST_DOING'
export const CHANGE_ROJECT_LIST_DONE = 'CHANGE_PROJECT_LIST_DONE'
export const CHANGE_PROJECT_LIST_ERROR = 'CHANGE_PROJECT_LIST_ERROR'
export const CHANGE_PROJECT_LIST_INIT = 'CHANGE_PROJECT_LIST_INIT'