
export const CHECK_POINT_INIT = 'CHECK_POINT_INIT';

export const CHECK_POINT_RESET = 'CHECK_POINT_RESET';

export const CHECK_POINT_LOAD = 'CHECK_POINT_LOAD';

export const CHECK_POINT_TO_NEW_QUALITY = 'CHECK_POINT_TO_NEW_QUALITY';
export const CHECK_POINT_TO_INFO = 'CHECK_POINT_TO_INFO';
export const CHECK_POINT_TO_QUALITY_LIST = 'CHECK_POINT_TO_INFO';
