export const DOC_MARKUP_TYPE_LOADING = 'DOC_MARKUP_TYPE_LOADING';
export const DOC_MARKUP_TYPE_LOADING_SUCCESS = 'DOC_MARKUP_TYPE_LOADING_SUCCESS';
export const DOC_MARKUP_TYPE_LOADING_FAIL = 'DOC_MARKUP_TYPE_LOADING_FAIL';

export const DOC_MARKUP_TYPE_LOADING_COMMENTS = 'DOC_MARKUP_TYPE_LOADING_COMMENTS';
export const DOC_MARKUP_TYPE_LOAD_COMMENTS_SUCCESS = 'DOC_MARKUP_TYPE_LOAD_COMMENTS_SUCCESS';
export const DOC_MARKUP_TYPE_LOAD_COMMENTS_FAIL = 'DOC_MARKUP_TYPE_LOAD_COMMENTS_FAIL';
export const DOC_MARKUP_TYPE_LOAD_COMMENTS_COMPLETE = 'DOC_MARKUP_TYPE_LOAD_COMMENTS_COMPLETE';

export const DOC_MARKUP_TYPE_SENDING_COMMENTS = 'DOC_MARKUP_TYPE_SENDING_COMMENTS';
export const DOC_MARKUP_TYPE_SEND_COMMENTS_SUCCESS = 'DOC_MARKUP_TYPE_SEND_COMMENTS_SUCCESS';
export const DOC_MARKUP_TYPE_SEND_COMMENTS_FAIL = 'DOC_MARKUP_TYPE_SEND_COMMENTS_FAIL';

export const DOC_MARKUP_LIST_TYPES = [
    { title: "全部批注", key: "all" },
    { title: "我的批注", key: "my" },
    { title: "@我的", key: "@me" }
]