
export const EQUIPMENT_LIST_DOING = 'EQUIPMENT_LIST_DOING'
export const EQUIPMENT_LIST_DONE = 'EQUIPMENT_LIST_DONE'
export const EQUIPMENT_LIST_ERROR = 'EQUIPMENT_LIST_ERROR'
export const EQUIPMENT_LIST_INIT = 'EQUIPMENT_LIST_INIT'
// export const EQUIPMENT_LIST_RETRY = 'EQUIPMENT_LIST_RETRY'