
export const EQUIPMENT_INFO_DOING = 'EQUIPMENT_INFO_DOING'
export const EQUIPMENT_INFO_DONE = 'EQUIPMENT_INFO_DONE'
export const EQUIPMENT_INFO_ERROR = 'EQUIPMENT_INFO_ERROR'
export const EQUIPMENT_INFO_INIT = 'EQUIPMENT_INFO_INIT'
// export const EQUIPMENT_INFO_RETRY = 'EQUIPMENT_INFO_RETRY'