
export const EQUIPMENT_NEW_DOING = 'EQUIPMENT_NEW_DOING'
export const EQUIPMENT_NEW_DONE = 'EQUIPMENT_NEW_DONE'
export const EQUIPMENT_NEW_ERROR = 'EQUIPMENT_NEW_ERROR'
export const EQUIPMENT_NEW_INIT = 'EQUIPMENT_NEW_INIT'