export const NEW_QUALITY_LOADING_START = 'NEW_QUALITY_LOADING_START';
export const NEW_QUALITY_LOADING_DONE = 'NEW_QUALITY_LOADING_DONE';
export const NEW_QUALITY_LOADING_ERROR = 'NEW_QUALITY_LOADING_ERROR';
export const NEW_QUALITY_RESET = 'NEW_QUALITY_RESET';