
export const PROJECT_LIST_DOING = 'PROJECT_LIST_DOING'
export const PROJECT_LIST_DONE = 'PROJECT_LIST_DONE'
export const PROJECT_LIST_ERROR = 'PROJECT_LIST_ERROR'
export const PROJECT_LIST_INIT = 'PROJECT_LIST_INIT'
// export const PROJECT_LIST_RETRY = 'PROJECT_LIST_RETRY'