
export const QUALITY_LIST_DOING = 'QUALITY_LIST_DOING'
export const QUALITY_LIST_DONE = 'QUALITY_LIST_DONE'
export const QUALITY_LIST_ERROR = 'QUALITY_LIST_ERROR'
export const QUALITY_LIST_INIT = 'QUALITY_LIST_INIT'
// export const QUALITY_LIST_RETRY = 'QUALITY_LIST_RETRY'