
export const QUALITY_INFO_DOING = 'QUALITY_INFO_DOING'
export const QUALITY_INFO_DONE = 'QUALITY_INFO_DONE'
export const QUALITY_INFO_ERROR = 'QUALITY_INFO_ERROR'
export const QUALITY_INFO_INIT = 'QUALITY_INFO_INIT'
// export const QUALITY_INFO_RETRY = 'QUALITY_INFO_RETRY'