export const REVIEW_REPAIR_LOAD_DETAIL = 'REVIEW_REPAIR_LOAD_DETAIL';
export const REVIEW_REPAIR_LOAD_REVIEWiNFO = 'REVIEW_REPAIR_LOAD_REVIEWiNFO';
export const REVIEW_REPAIR_LOAD_ERROR = 'REVIEW_REPAIR_LOAD_ERROR';
export const REVIEW_REPAIR_INIT = 'REVIEW_REPAIR_INIT';




