export const REVIEW_REPAIR_LOAD_DETAIL = 'REVIEW_REPAIR_LOAD_DETAIL';
export const REVIEW_REPAIR_LOAD_EDITINFO = 'REVIEW_REPAIR_LOAD_EDITINFO';
export const REVIEW_REPAIR_LOAD_ERROR = 'REVIEW_REPAIR_LOAD_ERROR';
export const REVIEW_REPAIR_INIT = 'REVIEW_REPAIR_INIT';




