export const SEARCH_QUALITY_START = 'SEARCH_QUALITY_START';
export const SEARCH_QUALITY_DONE = 'SEARCH_QUALITY_DONE';
export const SEARCH_EQUIPMENT_DONE = 'SEARCH_EQUIPMENT_DONE';
export const LOAD_SEARCH_HISTORY = 'LOAD_SEARCH_HISTORY';