/**
 * 页面入口
 */
// 0新建检查单 1检查单编辑状态 2详情查看  3质检单模型模式  4新建材设进场 5新增材设进场编辑状态  6材设模型模式

export const PAGE_TYPE_NEW_QUALITY = 'PAGE_TYPE_NEW_QUALITY';

export const PAGE_TYPE_EDIT_QUALITY = 'PAGE_TYPE_EDIT_QUALITY';

export const PAGE_TYPE_DETAIL = 'PAGE_TYPE_DETAIL';

export const PAGE_TYPE_QUALITY_MODEL = 'PAGE_TYPE_QUALITY_MODEL';

export const PAGE_TYPE_NEW_EQUIPMENT = 'PAGE_TYPE_NEW_EQUIPMENT';

export const PAGE_TYPE_EDIT_EQUIPMENT = 'PAGE_TYPE_EDIT_EQUIPMENT';

export const PAGE_TYPE_EQUIPMENT_MODEL = 'PAGE_TYPE_EQUIPMENT_MODEL';




